services:
  postgres:
    image: postgres:15
    container_name: stables_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: |
      bash -c "
      docker-entrypoint.sh postgres &
      until pg_isready -h localhost -p 5432 -U ${POSTGRES_USER}; do
        echo 'Waiting for PostgreSQL to be ready...'
        sleep 2
      done
      psql -v ON_ERROR_STOP=1 --username '${POSTGRES_USER}' --dbname '${POSTGRES_DB}' <<-EOSQL
        ALTER USER postgres PASSWORD '${POSTGRES_PASSWORD}';
        GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO postgres;
      EOSQL
      echo 'PostgreSQL initialization completed with password from environment variable'
      wait
      "
    restart: unless-stopped

volumes:
  postgres_data:
