version: 2

sources:
  - name: raw_usde_contracts
    description: "USDe contract data across all chains"
    schema: ethena_raw
    tables:
      - name: usde_contract_logs
        description: "Raw log data from USDE contract"
        columns:
          - name: topics
            description: "JSON array of topics"
            tests:
              - not_null
          - name: address
            description: "Contract address"
            tests:
              - not_null
          - name: data
            description: "Log data"
          - name: block_number
            description: "Block number"
            tests:
              - not_null
          - name: block_hash
            description: "Block hash"
          - name: time_stamp
            description: "Timestamp"
          - name: gas_price
            description: "Gas price"
          - name: gas_used
            description: "Gas used"
          - name: log_index
            description: "Log index"
          - name: transaction_hash
            description: "Transaction hash"
          - name: transaction_index
            description: "Transaction index"
      - name: mint_redeem_v2_contract_logs
        description: "Raw log data from mint/redeem v2 contract"
        columns:
          - name: topics
            description: "JSON array of topics"
            tests:
              - not_null
          - name: address
            description: "Contract address"
            tests:
              - not_null
          - name: data
            description: "Log data"
          - name: block_number
            description: "Block number"
            tests:
              - not_null
          - name: block_hash
            description: "Block hash"
          - name: time_stamp
            description: "Timestamp"
          - name: gas_price
            description: "Gas price"
          - name: gas_used
            description: "Gas used"
          - name: log_index
            description: "Log index"
          - name: transaction_hash
            description: "Transaction hash"
          - name: transaction_index
            description: "Transaction index"
      - name: mint_redeem_v1_contract_logs
        description: "Raw log data from mint/redeem v1 contract"
        columns:
          - name: topics
            description: "JSON array of topics"
            tests:
              - not_null
          - name: address
            description: "Contract address"
            tests:
              - not_null
          - name: data
            description: "Log data"
          - name: block_number
            description: "Block number"
            tests:
              - not_null
          - name: block_hash
            description: "Block hash"
          - name: time_stamp
            description: "Timestamp"
          - name: gas_price
            description: "Gas price"
          - name: gas_used
            description: "Gas used"
          - name: log_index
            description: "Log index"
          - name: transaction_hash
            description: "Transaction hash"
          - name: transaction_index
            description: "Transaction index"
