"""add_supply_metrics

Revision ID: 02b522b04e7b
Revises: 265fc53d6c9e
Create Date: 2025-04-02 15:47:52.458500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b522b04e7b'
down_revision: Union[str, None] = '265fc53d6c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aggregated_metrics', sa.Column('chain_id', sa.Integer(), nullable=False))
    op.add_column('aggregated_metrics', sa.Column('circulating_supply', sa.Float(), nullable=True))
    op.add_column('aggregated_metrics', sa.Column('supply_change_24h', sa.Float(), nullable=True))
    op.add_column('aggregated_metrics', sa.Column('supply_change_7d', sa.Float(), nullable=True))
    op.add_column('aggregated_metrics', sa.Column('supply_change_30d', sa.Float(), nullable=True))
    op.alter_column('aggregated_metrics', 'total_transfer_volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('aggregated_metrics', 'transfer_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'aggregated_metrics', 'chains', ['chain_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aggregated_metrics', type_='foreignkey')
    op.alter_column('aggregated_metrics', 'transfer_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('aggregated_metrics', 'total_transfer_volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('aggregated_metrics', 'supply_change_30d')
    op.drop_column('aggregated_metrics', 'supply_change_7d')
    op.drop_column('aggregated_metrics', 'supply_change_24h')
    op.drop_column('aggregated_metrics', 'circulating_supply')
    op.drop_column('aggregated_metrics', 'chain_id')
    # ### end Alembic commands ###
