"""Add relationship between AggregatedMetrics and Stablecoin

Revision ID: 265fc53d6c9e
Revises: 6474237182cf
Create Date: 2025-04-01 18:36:23.830358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '265fc53d6c9e'
down_revision: Union[str, None] = '6474237182cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
