"""Initial migration

Revision ID: 85499c78df40
Revises: 
Create Date: 2025-04-01 14:54:03.283992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85499c78df40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('rpc_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_id')
    )
    op.create_index(op.f('ix_chains_id'), 'chains', ['id'], unique=False)
    op.create_index(op.f('ix_chains_name'), 'chains', ['name'], unique=True)
    op.create_table('stablecoins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('addresses', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stablecoins_id'), 'stablecoins', ['id'], unique=False)
    op.create_index(op.f('ix_stablecoins_symbol'), 'stablecoins', ['symbol'], unique=True)
    op.create_table('aggregated_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stablecoin_id', sa.Integer(), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('minted', sa.Float(), nullable=True),
    sa.Column('burned', sa.Float(), nullable=True),
    sa.Column('transferred', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ),
    sa.ForeignKeyConstraint(['stablecoin_id'], ['stablecoins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aggregated_metrics_id'), 'aggregated_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_aggregated_metrics_timestamp'), 'aggregated_metrics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aggregated_metrics_timestamp'), table_name='aggregated_metrics')
    op.drop_index(op.f('ix_aggregated_metrics_id'), table_name='aggregated_metrics')
    op.drop_table('aggregated_metrics')
    op.drop_index(op.f('ix_stablecoins_symbol'), table_name='stablecoins')
    op.drop_index(op.f('ix_stablecoins_id'), table_name='stablecoins')
    op.drop_table('stablecoins')
    op.drop_index(op.f('ix_chains_name'), table_name='chains')
    op.drop_index(op.f('ix_chains_id'), table_name='chains')
    op.drop_table('chains')
    # ### end Alembic commands ###
