name: "ethena"
version: "1.0"
config-version: 2

model-paths: ["models"]
macro-paths: ["../macros"]
profile: "ethena"

models:
  ethena:
    +materialized: table
    staging:
      +schema: staging
    marts:
      +schema: marts
